### PR TITLE
Add the Karma Jasmine HTML reporter plugin

### PR DESCRIPTION
**Pull request by andy-armstrong**
This plugin extends Karma's debug page to enumerate the tests that were run, and to show the results in
green if they passed or red if they failed. You can also click on an individual test or suite and run just those.

More details from the web site:

https://www.npmjs.com/package/karma-jasmine-html-reporter

@AlasdairSwan @dsjen please review.

### CODE REVIEW

**Comment by andy-armstrong** [comment]
Here's a screenshot:

image

**Comment by dsjen** [comment]
I just tested that out and it's awesome!!!  :100: :dancers: :rabbit:

**Comment by benpatterson** [comment]
Just saw this on my stream (I'm lurking on this repo!) I love this change. Thank all you guys for working a healthy dev/test infrastructure into this repo. :heart:

**Comment by andy-armstrong** [comment]
I forgot to mention that @jzoldak was the one who found this plugin for me. I'm introducing it into the ORA2 repo so that I have a prayer of debugging its large suite of Jasmine tests!

https://github.com/edx/edx-ora2/pull/740

**Comment by AlasdairSwan** [comment]
Nice :+1:

**Pull request merged**
