### PR TITLE
Update README to gulp test-debug (with a hyphen)

### PR DESCRIPTION
**Pull request by kevinrobinson**
A tiny documentation fix: https://github.com/edx/edx-ui-toolkit/blob/master/gulp/tasks/test-debug.js#L9

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @kevinrobinson! I've created [OSPR-1215](https://openedx.atlassian.net/browse/OSPR-1215) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-ui-toolkit/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by kevinrobinson** [comment]
@edx-webhook Hey robot buddy!  I signed the agreement and emailed it to legal@edx.org, so hopefully you'll notice that soon :)

**Comment by nedbat** [comment]
@andy-armstrong this seems right on the face of it, I'm merging.  Feel free to correct if this is more complex than @kevinrobinson or I knew :)

**Comment by kevinrobinson** [comment]
Thanks @nedbat!

**Comment by andy-armstrong** [comment]
Thanks, @kevinrobinson. That was my oversight when I renamed the gulp task. :+1:

**Comment by andy-armstrong** [comment]
@kevinrobinson I'm also intrigued as to what brings you to the UI Toolkit...

**Comment by kevinrobinson** [comment]
@andy-armstrong no problemo!  just poking around mostly :)

**Comment by andy-armstrong** [comment]
Thanks for picking up after me on your way through :-) Let me know if you have any questions about the UI Toolkit.

**Comment by kevinrobinson** [comment]
will do!

**Pull request merged**
