### PR TITLE
[WIP] Publish JavaScript API documentation

### PR DESCRIPTION
**Pull request by andy-armstrong**
https://openedx.atlassian.net/browse/FEDX-3

I've done some experimentation and have generated some very rudimentary JavaScript documentation for the UI Toolkit. You can see a hosted version of it here:

http://ux-test.edx.org/andya/ui-toolkit-doc/

There's a lot more to investigate here:
 - how should this content look? I don't think the JSDoc style will scale very well
 - can we use the Pattern Library to make the doc look edX branded?
 - how should we publish it? I'm thinking of using GitHub Pages and giving it a URL like http://ui-toolkit.edx.org
   - I requested the domain: https://openedx.atlassian.net/servicedesk/customer/portal/3/DEVOPS-3781
 - what is the best way to publish this to GitHub Pages?
   http://stackoverflow.com/questions/35800068/how-can-i-generate-javascript-api-documentation-for-github-pages
 - how can we integrate generated and human written documentation into one seamless whole?

FYI @pdesjardins @lamagnifica @AlasdairSwan @dsjen @dan-f @cahrens @symbolist @benpatterson

### CODE REVIEW

**Comment by edx-webhook** [comment]
## PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

## Sandbox
- [ ] Build a sandbox for your branch and add a link here

## Testing
- [ ] i18n
- [ ] RTL
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

## Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2
- [ ] Docs review (required for UI strings/error messages)
- [ ] UX review
- [ ] Accessibility review
- [ ] Product review

## Documentation considerations
- [ ] Are there user visible changes? If so, list who is affected, and include a pointer to the relevant code.
- [ ] Should this be mentioned in the release notes? If so, make sure that you included a description.

## DevOps assistance
If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket

FYI: Tag anyone who might be interested in this PR here.

## Post-review
- [ ] Squash commits

**Comment by dsjen** [comment]
Oh wow!  This is very exciting. :)

**Comment by cahrens** [comment]
I find the current styling hard to skim. It would be good if there was an index of the methods at the top so you can quickly see what is supported and then jump to the more detailed doc.

**Comment by andy-armstrong** [comment]
@cahrens I agree that the styling is awful (bland and hard to navigate). This is the default for JSDoc so we'll have to investigate what our options are. I was hoping we could get something like the React API docs:

https://facebook.github.io/react/docs/top-level-api.html

**Comment by andy-armstrong** [comment]
I tried a different library (docco) which has a very different approach. This is the library used by Underscore and Backbone. It is more useful for viewing the code than for understanding an API, I think.

http://ux-test.edx.org/andya/docco/disclosure-view-spec.html

You can read more about it here:

https://github.com/jashkenas/docco

**Comment by andy-armstrong** [comment]
@bjacobel FYI

**Comment by andy-armstrong** [comment]
Closing in favor of https://github.com/edx/edx-ui-toolkit/pull/55

**Pull request closed without merging**
