### PR TITLE
Reorganize file structure for npm package

### PR DESCRIPTION
**Pull request by andy-armstrong**
I've reorganized the file structure as we discussed to better suit npm packages.

@AlasdairSwan @dsjen please review.

### CODE REVIEW

**Comment by edx-webhook** [comment]
## PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

## Sandbox
- [ ] Build a sandbox for your branch and add a link here

## Testing
- [ ] i18n
- [ ] RTL
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

## Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2
- [ ] Docs review (required for UI strings/error messages)
- [ ] UX review
- [ ] Accessibility review
- [ ] Product review

## Documentation considerations
- [ ] Are there user visible changes? If so, list who is affected, and include a pointer to the relevant code.
- [ ] Should this be mentioned in the release notes? If so, make sure that you included a description.

## DevOps assistance
If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket

FYI: Tag anyone who might be interested in this PR here.

## Post-review
- [ ] Squash commits

**Comment by AlasdairSwan** [comment]
Nice, once tests pass :+1:

**Comment by dsjen** [comment]
:+1:

**Comment by andy-armstrong** [comment]
FYI @dan-f @peter-fogg, we merged this reorganization of the UI Toolkit file hierarchy as part of the hackathon.

**Comment by dan-f** [comment]
@andy-armstrong We should follow the `semver` spec, which stipulates that this change should result in a major version bump, since changing file paths counts as "incompatible API changes". Anyone who had pinned to a version of this library permitting minor level updates will see their builds fail.

**Comment by dan-f** [comment]
I can bump the version if you want. Other than updating the `package.json` and `CHANGELOG`, do I also need to do a GitHub release?

**Comment by andy-armstrong** [comment]
We're still at version 0, so those rules don't apply. Here's what semver.org says:

Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by dan-f** [comment]
:+1:

**Pull request merged**
