### PR TITLE
Team/add coveralls

### PR DESCRIPTION
**Pull request by benpatterson**

### CODE REVIEW

**Comment by dsjen** [comment]
Looks like this worked. :+1: 

You may want to squash commits before merging.

**Comment by benpatterson** [comment]
oh @dsjen I'm afraid if you look at the logs, that this did not work :( So this should remain open. Or I can just close it altogether.

**Comment by dsjen** [comment]
Oh, that's too bad... :(

**Comment by andy-armstrong** [comment]
@benpatterson Can we close this PR now, since coveralls made it in through a different PR?

**Comment by benpatterson** [comment]
Yes! Sorry I thought I closed it. Closing now!

**Pull request closed without merging**
